name: Deploy (roydev.xyz)
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'     

      - name: Install Dependencies
        run: npm ci

      - name: Install Hexo CLI
        run: npm install -g hexo-cli

      - name: Build
        run: |
          npm run clean
          npm run build

      - uses: actions/checkout@v4 
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: public    

        

  # deploy:
  #   name: Deploy
  #   steps:

  #     - name: Deploy
  #       uses: cloudflare/wrangler-action@v3
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #         command: pages deploy public --project-name=roydevxyz
  #         wranglerVersion: '3.90.0'