name: Deploy (roydev.xyz)

on:
  push:
    branches:
      - master        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  
          cache: 'npm'        

      - name: Install Dependencies
        run: |
          npm ci 

      - name: Install Hexo CLI globally 
        run: npm install -g hexo-cli

      - name: Generate Static Files
        run: |
          npm run clean
          npm run build

  deploy: 
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_BLOG_API_TOKEN }}
          accountId: ${{ secrets.CF_BLOG_ACCOUNT_ID }}